name: 'Build'

on:
  - push
  - pull_request

jobs:
  setup:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

  forge_setup:
    if: "contains(github.ref_name, 'forge')"
    runs-on: ubuntu-latest
    steps:
      - name: Validate no assets
        run: test ! -d ./src/generated
      - name: Generate assets
        run: ./gradlew runData
        continue-on-error: true
      - name: Validate assets
        run: test -d ./src/generated -a -f ./src/generated/resources/.cache/cache
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build with Gradle
        run: ./gradlew build
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: build/libs/
